title: SPYGlass
description: >-
  Development tools for vanilla Minecraft: Java Edition content creators.
baseurl: ""
url: https://spyglassmc.com
github_username: SPYGlassMC

# Build settings
theme: minima
# plugins:
  # - jekyll-feed

exclude:
  - .github
  - vendor

##
# Parameters for WikiToJekyll
# Used by Rake:wikisub, Rake:wiki and wikiLinks generator plugin
# https://github.com/djacquel/WikiToJekyll
##
wikiToJekyll:
  user_name: SPYGlassMC
  repository_name: spyglassmc.github.io
  deploy_remote: origin
  deploy_branch: master

  wiki_repository_url: https://github.com/SPYGlassMC/datapack-language-server.wiki.git
  wiki_source: "_wiki"
  wiki_dest: "wiki"

  commit_and_push: false
